name: crc-analysis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base>=4.3
  - bioconductor-geoquery
  - bioconductor-limma
  - bioconductor-reactomepa
  - bioconductor-enrichplot
  - bioconductor-org.hs.eg.db
  - r-dplyr
  - r-tidyr
  - r-stringr
  - r-tibble
  - r-ggplot2
  - r-ggrepel
  - r-pheatmap
  - r-rmarkdown
  - r-knitr
